#include <stdio.h>
#include <stdlib.h>
#include "da.h"
#include "integer.h"
#include "real.h"
#include "string.h"
extern long random(void);
extern void srandom(unsigned int seed);

int
main(void)
    {
    printf("DA tester: 0,4\n");
    printf("you can retrieve this test with:\n");
    printf("wget beastie.cs.ua.edu/cs201/testing/0/da-test-0-4.c\n");
    printf("\noutput:\n\n");
    DA *d = newDA(displayINTEGER);
    insertDA(d,newINTEGER(765));
    insertDA(d,newINTEGER(610));
    insertDA(d,newINTEGER(72));
    insertDA(d,newINTEGER(276));
    insertDA(d,newINTEGER(632));
    insertDA(d,newINTEGER(920));
    insertDA(d,newINTEGER(649));
    insertDA(d,newINTEGER(73));
    insertDA(d,newINTEGER(381));
    insertDA(d,newINTEGER(26));
    insertDA(d,newINTEGER(848));
    insertDA(d,newINTEGER(860));
    insertDA(d,newINTEGER(198));
    insertDA(d,newINTEGER(410));
    insertDA(d,newINTEGER(20));
    insertDA(d,newINTEGER(20));
    insertDA(d,newINTEGER(226));
    insertDA(d,newINTEGER(828));
    insertDA(d,newINTEGER(486));
    insertDA(d,newINTEGER(414));
    insertDA(d,newINTEGER(5));
    insertDA(d,newINTEGER(679));
    insertDA(d,newINTEGER(373));
    insertDA(d,newINTEGER(331));
    insertDA(d,newINTEGER(460));
    insertDA(d,newINTEGER(383));
    insertDA(d,newINTEGER(873));
    insertDA(d,newINTEGER(52));
    insertDA(d,newINTEGER(967));
    insertDA(d,newINTEGER(346));
    insertDA(d,newINTEGER(727));
    insertDA(d,newINTEGER(84));
    insertDA(d,newINTEGER(308));
    insertDA(d,newINTEGER(799));
    insertDA(d,newINTEGER(361));
    printf("array d:");
    visualizeDA(stdout,d);
    printf("\n");
    DA *e = newDA(displayINTEGER);
    insertDA(e,newINTEGER(940));
    insertDA(e,newINTEGER(71));
    insertDA(e,newINTEGER(10));
    insertDA(e,newINTEGER(365));
    insertDA(e,newINTEGER(453));
    insertDA(e,newINTEGER(37));
    insertDA(e,newINTEGER(213));
    insertDA(e,newINTEGER(665));
    insertDA(e,newINTEGER(235));
    insertDA(e,newINTEGER(623));
    insertDA(e,newINTEGER(37));
    insertDA(e,newINTEGER(607));
    insertDA(e,newINTEGER(201));
    insertDA(e,newINTEGER(865));
    insertDA(e,newINTEGER(93));
    insertDA(e,newINTEGER(615));
    insertDA(e,newINTEGER(222));
    insertDA(e,newINTEGER(773));
    insertDA(e,newINTEGER(988));
    insertDA(e,newINTEGER(553));
    insertDA(e,newINTEGER(585));
    insertDA(e,newINTEGER(723));
    insertDA(e,newINTEGER(427));
    insertDA(e,newINTEGER(989));
    insertDA(e,newINTEGER(42));
    insertDA(e,newINTEGER(773));
    insertDA(e,newINTEGER(716));
    insertDA(e,newINTEGER(127));
    insertDA(e,newINTEGER(433));
    insertDA(e,newINTEGER(868));
    insertDA(e,newINTEGER(488));
    insertDA(e,newINTEGER(373));
    insertDA(e,newINTEGER(939));
    insertDA(e,newINTEGER(850));
    insertDA(e,newINTEGER(90));
    insertDA(e,newINTEGER(744));
    insertDA(e,newINTEGER(887));
    insertDA(e,newINTEGER(303));
    insertDA(e,newINTEGER(761));
    insertDA(e,newINTEGER(474));
    insertDA(e,newINTEGER(278));
    insertDA(e,newINTEGER(798));
    insertDA(e,newINTEGER(433));
    insertDA(e,newINTEGER(479));
    insertDA(e,newINTEGER(663));
    insertDA(e,newINTEGER(527));
    insertDA(e,newINTEGER(94));
    insertDA(e,newINTEGER(886));
    insertDA(e,newINTEGER(652));
    insertDA(e,newINTEGER(434));
    insertDA(e,newINTEGER(791));
    insertDA(e,newINTEGER(589));
    insertDA(e,newINTEGER(158));
    insertDA(e,newINTEGER(218));
    insertDA(e,newINTEGER(578));
    insertDA(e,newINTEGER(552));
    insertDA(e,newINTEGER(343));
    insertDA(e,newINTEGER(646));
    insertDA(e,newINTEGER(679));
    insertDA(e,newINTEGER(776));
    insertDA(e,newINTEGER(514));
    insertDA(e,newINTEGER(519));
    insertDA(e,newINTEGER(501));
    insertDA(e,newINTEGER(806));
    insertDA(e,newINTEGER(370));
    insertDA(e,newINTEGER(591));
    insertDA(e,newINTEGER(550));
    insertDA(e,newINTEGER(609));
    insertDA(e,newINTEGER(246));
    insertDA(e,newINTEGER(312));
    printf("array e:");
    visualizeDA(stdout,e);
    printf("\n");
    printf("performing unionDA(d,e)\n");
    unionDA(d,e);
    printf("\n");
    printf("array d: ");
    displayDA(stdout,d);
    printf("\n");
    printf("array e: ");
    displayDA(stdout,e);
    printf("\n");
    printf("performing unionDA(d,e)\n");
    unionDA(d,e);
    printf("\n");
    printf("array d: ");
    displayDA(stdout,d);
    printf("\n");
    printf("array e: ");
    displayDA(stdout,e);
    printf("\n");
    printf("performing unionDA(e,d)\n");
    unionDA(e,d);
    printf("\n");
    printf("array d: ");
    displayDA(stdout,d);
    printf("\n");
    printf("array e: ");
    displayDA(stdout,e);
    printf("\n");
    return 0;
    }
