# Ian Braudaway
# makefile for assignment 0
DA_OBJS = integer.o real.o string.o da.o test-da.o
CDA_OBJS = integer.o real.o string.o cda.o test-cda.o
STACK_OBJS = integer.o real.o string.o da.o stack.o test-stack.o
QUEUE_OBJS = integer.o real.o string.o cda.o queue.o test-queue.o
DA0 = integer.o real.o string.o da.o da-test-0-0.o
DA1 = integer.o real.o string.o da.o da-test-0-1.o
DA2 = integer.o real.o string.o da.o da-test-0-2.o
DA3 = integer.o real.o string.o da.o da-test-0-3.o
DA4 = integer.o real.o string.o da.o da-test-0-4.o
DA5 = integer.o real.o string.o da.o da-test-0-5.o
DA6 = integer.o real.o string.o da.o da-test-0-6.o
DA7 = integer.o real.o string.o da.o da-test-0-7.o
DA8 = integer.o real.o string.o da.o da-test-0-8.o
DA9 = integer.o real.o string.o da.o da-test-0-9.o
CDA0 = integer.o real.o string.o cda.o cda-test-0-0.o
CDA1 = integer.o real.o string.o cda.o cda-test-0-1.o
CDA2 = integer.o real.o string.o cda.o cda-test-0-2.o
CDA3 = integer.o real.o string.o cda.o cda-test-0-3.o
CDA4 = integer.o real.o string.o cda.o cda-test-0-4.o
CDA5 = integer.o real.o string.o cda.o cda-test-0-5.o
CDA6 = integer.o real.o string.o cda.o cda-test-0-6.o
CDA7 = integer.o real.o string.o cda.o cda-test-0-7.o
CDA8 = integer.o real.o string.o cda.o cda-test-0-8.o
CDA9 = integer.o real.o string.o cda.o cda-test-0-9.o
CDA10 = integer.o real.o string.o cda.o cda-test-0-10.o
STACK0 = integer.o real.o string.o da.o stack.o stack-test-0-0.o
STACK1 = integer.o real.o string.o da.o stack.o stack-test-0-1.o
STACK2 = integer.o real.o string.o da.o stack.o stack-test-0-2.o
STACK3 = integer.o real.o string.o da.o stack.o stack-test-0-3.o
STACK4 = integer.o real.o string.o da.o stack.o stack-test-0-4.o
STACK5 = integer.o real.o string.o da.o stack.o stack-test-0-5.o
STACK6 = integer.o real.o string.o da.o stack.o stack-test-0-6.o
QUEUE0 = integer.o real.o string.o cda.o queue.o queue-test-0-0.o
QUEUE1 = integer.o real.o string.o cda.o queue.o queue-test-0-1.o
QUEUE2 = integer.o real.o string.o cda.o queue.o queue-test-0-2.o
QUEUE3 = integer.o real.o string.o cda.o queue.o queue-test-0-3.o
QUEUE4 = integer.o real.o string.o cda.o queue.o queue-test-0-4.o
QUEUE5 = integer.o real.o string.o cda.o queue.o queue-test-0-5.o
QUEUE6 = integer.o real.o string.o cda.o queue.o queue-test-0-6.o
OPTS = -Wall -Wextra -std=c99 -g -c 
LOPTS = -Wall -Wextra -std=c99 -g
CC = gcc

all : test-da test-stack test-cda test-queue test-da-0 test-da-1 test-da-2 test-da-3 test-da-4 test-da-5 test-da-6 test-da-7 test-da-8 test-da-9 test-cda-0 test-cda-1 test-cda-2 test-cda-3 test-cda-4 test-cda-5 test-cda-6 test-cda-7 test-cda-8 test-cda-9 test-cda-10 test-stack-0 test-stack-1 test-stack-2 test-stack-3 test-stack-4 test-stack-5 test-stack-6 test-queue-0 test-queue-1 test-queue-2 test-queue-3 test-queue-4 test-queue-5 test-queue-6

test-da : $(DA_OBJS)
	$(CC) $(LOPTS) $(DA_OBJS) -o test-da

test-stack : $(STACK_OBJS)
	$(CC) $(LOPTS) $(STACK_OBJS) -o test-stack

test-cda : $(CDA_OBJS)
	$(CC) $(LOPTS) $(CDA_OBJS) -o test-cda

test-queue : $(QUEUE_OBJS)
	$(CC) $(LOPTS) $(QUEUE_OBJS) -o test-queue

test-da-0 : $(DA0)
	$(CC) $(LOPTS) $(DA0) -o test-da-0

test-da-1 : $(DA1)
	$(CC) $(LOPTS) $(DA1) -o test-da-1
	
test-da-2 : $(DA2)
	$(CC) $(LOPTS) $(DA2) -o test-da-2
	
test-da-3 : $(DA3)
	$(CC) $(LOPTS) $(DA3) -o test-da-3
	
test-da-4 : $(DA4)
	$(CC) $(LOPTS) $(DA4) -o test-da-4
	
test-da-5 : $(DA5)
	$(CC) $(LOPTS) $(DA5) -o test-da-5
	
test-da-6 : $(DA6)
	$(CC) $(LOPTS) $(DA6) -o test-da-6
	
test-da-7 : $(DA7)
	$(CC) $(LOPTS) $(DA7) -o test-da-7
	
test-da-8 : $(DA8)
	$(CC) $(LOPTS) $(DA8) -o test-da-8
	
test-da-9 : $(DA9)
	$(CC) $(LOPTS) $(DA9) -o test-da-9

test-cda-0 : $(CDA0)
	$(CC) $(LOPTS) $(CDA0) -o test-cda-0

test-cda-1 : $(CDA1)
	$(CC) $(LOPTS) $(CDA1) -o test-cda-1
	
test-cda-2 : $(CDA2)
	$(CC) $(LOPTS) $(CDA2) -o test-cda-2
	
test-cda-3 : $(CDA3)
	$(CC) $(LOPTS) $(CDA3) -o test-cda-3
	
test-cda-4 : $(CDA4)
	$(CC) $(LOPTS) $(CDA4) -o test-cda-4
	
test-cda-5 : $(CDA5)
	$(CC) $(LOPTS) $(CDA5) -o test-cda-5
	
test-cda-6 : $(CDA6)
	$(CC) $(LOPTS) $(CDA6) -o test-cda-6
	
test-cda-7 : $(CDA7)
	$(CC) $(LOPTS) $(CDA7) -o test-cda-7
	
test-cda-8 : $(CDA8)
	$(CC) $(LOPTS) $(CDA8) -o test-cda-8
	
test-cda-9 : $(CDA9)
	$(CC) $(LOPTS) $(CDA9) -o test-cda-9
	
test-cda-10 : $(CDA10)
	$(CC) $(LOPTS) $(CDA10) -o test-cda-10
	
test-stack-0 : $(STACK0)
	$(CC) $(LOPTS) $(STACK0) -o test-stack-0

test-stack-1 : $(STACK1)
	$(CC) $(LOPTS) $(STACK1) -o test-stack-1
	
test-stack-2 : $(STACK2)
	$(CC) $(LOPTS) $(STACK2) -o test-stack-2
	
test-stack-3 : $(STACK3)
	$(CC) $(LOPTS) $(STACK3) -o test-stack-3
	
test-stack-4 : $(STACK4)
	$(CC) $(LOPTS) $(STACK4) -o test-stack-4
	
test-stack-5 : $(STACK5)
	$(CC) $(LOPTS) $(STACK5) -o test-stack-5
	
test-stack-6 : $(STACK6)
	$(CC) $(LOPTS) $(STACK6) -o test-stack-6

test-queue-0 : $(QUEUE0)
	$(CC) $(LOPTS) $(QUEUE0) -o test-queue-0

test-queue-1 : $(QUEUE1)
	$(CC) $(LOPTS) $(QUEUE1) -o test-queue-1
	
test-queue-2 : $(QUEUE2)
	$(CC) $(LOPTS) $(QUEUE2) -o test-queue-2
	
test-queue-3 : $(QUEUE3)
	$(CC) $(LOPTS) $(QUEUE3) -o test-queue-3
	
test-queue-4 : $(QUEUE4)
	$(CC) $(LOPTS) $(QUEUE4) -o test-queue-4
	
test-queue-5 : $(QUEUE5)
	$(CC) $(LOPTS) $(QUEUE5) -o test-queue-5
	
test-queue-6 : $(QUEUE6)
	$(CC) $(LOPTS) $(QUEUE6) -o test-queue-6
	
real.o : real.c real.h
	$(CC) $(OPTS) real.c 
	
integer.o : integer.c integer.h
	$(CC) $(OPTS) integer.c

string.o : string.c string.h
	$(CC) $(OPTS) string.c

da.o : da.c da.h
	$(CC) $(OPTS) da.c

cda.o : cda.c cda.h
	$(CC) $(OPTS) cda.c

stack.o : stack.c stack.h
	$(CC) $(OPTS) stack.c

queue.o : queue.c queue.h
	$(CC) $(OPTS) queue.c

clean :
	rm -f $(DA_OBJS) $(STACK_OBJS) $(CDA_OBJS) $(QUEUE_OBJS) $(DA0) $(DA1) $(DA2) $(DA3) $(DA4) $(DA5) $(DA6) $(DA7) $(DA8) $(DA9) $(CDA0) $(CDA1) $(CDA2) $(CDA3) $(CDA4) $(CDA5) $(CDA6) $(CDA7) $(CDA8) $(CDA9) $(CDA10) $(STACK0) $(STACK1) $(STACK2) $(STACK3) $(STACK4) $(STACK5) $(STACK6) $(QUEUE0) $(QUEUE1) $(QUEUE2) $(QUEUE3) $(QUEUE4) $(QUEUE5) $(QUEUE6) ./test-da ./test-cda ./test-stack ./test-queue ./test-da-0 ./test-da-1 ./test-da-2 ./test-da-3 ./test-da-4 ./test-da-5 ./test-da-6 ./test-da-7 ./test-da-8 ./test-da-9 ./test-cda-0 ./test-cda-1 ./test-cda-2 ./test-cda-3 ./test-cda-4 ./test-cda-5 ./test-cda-6 ./test-cda-7 ./test-cda-8 ./test-cda-9 ./test-cda-10 ./test-stack-0 ./test-stack-1 ./test-stack-2 ./test-stack-3 ./test-stack-4 ./test-stack-5 ./test-stack-6 ./test-queue-0 ./test-queue-1 ./test-queue-2 ./test-queue-3 ./test-queue-4 ./test-queue-5 ./test-queue-6

test :
	./test-da 
	./test-stack 
	./test-cda 
	./test-queue
	./test-da-0
	./test-da-1
	./test-da-2
	./test-da-3
	./test-da-4
	./test-da-5
	./test-da-6
	./test-da-7
	./test-da-8
	./test-da-9
	./test-cda-0
	./test-cda-1
	./test-cda-2
	./test-cda-3
	./test-cda-4
	./test-cda-5
	./test-cda-6
	./test-cda-7
	./test-cda-8
	./test-cda-9
	./test-cda-10
	./test-stack-0
	./test-stack-1
	./test-stack-2
	./test-stack-3
	./test-stack-4
	./test-stack-5
	./test-stack-6
	./test-queue-0
	./test-queue-1
	./test-queue-2
	./test-queue-3
	./test-queue-4
	./test-queue-5
	./test-queue-6
